# Generated by Django 6.0 on 2026-01-18 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offering_type', models.CharField(choices=[('P', 'Product'), ('S', 'Service')], default='P', max_length=1)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('stock_status', models.CharField(choices=[('I', 'In stock'), ('O', 'Out of stock'), ('D', 'Made on demand')], max_length=1)),
                ('hobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.hobby')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offering',
                'verbose_name_plural': 'Offerings',
            },
        ),
    ]
