# Generated by Django 6.0 on 2026-01-17 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='votes',
        ),
        migrations.AlterField(
            model_name='vote',
            name='hobby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='marketplace.hobby'),
        ),
    ]
