# Generated by Django 6.0 on 2025-12-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_hobby_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hobby',
            options={'verbose_name': 'Hobby', 'verbose_name_plural': 'Hobbies'},
        ),
        migrations.AlterModelOptions(
            name='userhashobby',
            options={'verbose_name': 'Claimed hobby', 'verbose_name_plural': 'Claimed hobbies'},
        ),
        migrations.AddField(
            model_name='hobby',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
