# Generated by Django 6.0 on 2026-01-18 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_offering'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering',
            name='stock_status',
            field=models.CharField(blank=True, choices=[('I', 'In stock'), ('O', 'Out of stock'), ('D', 'Made on demand')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected'), ('T', 'Too low price')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offered_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_trades', to='marketplace.offering')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_trades', to='marketplace.offering')),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
            },
        ),
    ]
