# Generated by Django 6.0 on 2025-12-13 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_hobby_options_alter_userhashobby_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hobby',
            old_name='hobby_output',
            new_name='output_type',
        ),
    ]
